### ISSUE TITLE
Complete Docker setup

### ISSUE THREAD

**Issue by czosel** [SchweizerischeBundesbahnen/BCNFStar#343]
Just an idea from looking at the current Docker setup: Would it make sense to add a postgres DB and potentially even java/metanome to the Docker setup? Ideally, users of this project would not need to install anything on their local machine. Or does anything speak against this (apart from the effort to get this to work, of course :wink:)?

**Comment by czosel** [comment]
Sorry, I totally missed that the Java environment. In that case my question is just about the database: Why not eliminate the need for a local postgres installation with configuration etc. by running postgres in a dedicated Docker container? I understand that in production you might not want to run postgres in Docker in favor of a dedicated cluster, but in development it is very convenient to not have to worry about installation, configuration etc.

Or is the database in this case always something external, i.e. the object that is being manipulated, so it doesn’t make sense to add a postgres container?

**Comment by 23mafi** [comment]
Hello, it is as you suspected. The database should be able to be variable. For example, to persist our edited schema, we generate a sql file and it could be executed on the database. When executed, a new schema is created on the database. It should also be possible to change the database, because maybe someone wants to change a schema that is in another database, which I think is not possible if Postgres is included in the cointainer.
